name: Deployment pipeline

on:
  push:
    branches:
      - main
  
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_DEPLOY: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build
      
      - name: Build Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
            severity: info
            details: Build succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Build Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
            severity: error
            details: Build failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Run tests
        run: npm run test
      
  simple_deployment_pipeline:
    needs: [simple_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Deploy
        if: ${{ github.env.SKIP_DEPLOY == 'true' }}
        run: curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        
      - name: Deploy Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
            severity: info
            details: Deploy succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Bump version and push tag
        if: ${{ github.env.SKIP_DEPLOY == 'true' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

